version: '3.7'

services:

  webserver:
    container_name: app-frontend-webserver
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - '.:/application'
      - '/application/node_modules'
    ports:
      - '80:8080'
    restart: unless-stopped